$(document).ready ->
  $(".upload_img1").click ->
    $(".upload_field1").trigger "click"
  $(".upload_img2").click ->
    $(".upload_field2").trigger "click"
  $(".upload_img3").click ->
    $(".upload_field3").trigger "click"
  $(".upload_img4").click ->
    $(".upload_field4").trigger "click"
  $(".upload_img5").click ->
    $(".upload_field5").trigger "click"